added activities to vessel profile
GlobalFishingWatch/frontend pull request #2106
Opened 2023-06-23 04:28 UTC by fertandil87

2023-06-26 21:45 UTC, j8seangel requested changes
Some high-level comments, lets sync again once you have more time to polish and review

2023-06-26 21:45 UTC, j8seangel commented on apps/fishing-map/features/vessel/activity/activity-by-type/activity-by-type.hook.ts
> +  const eventsByType = useMemo(
I want all the grouping and filtering logic in the selector and not spread in the app. Also, this is not performant at all.
Could you take a look?

2023-06-26 21:45 UTC, j8seangel commented on apps/fishing-map/features/vessel/activity/activity-by-type/activity-by-type.selectors.ts
> +                  ? t('event.hourAbbreviated', '{{count}}h', { count: duration.hours })
Translations can't be used in selectors as changing the language doesn't trigger the update

2023-06-27 16:46 UTC, fertandil87 commented on apps/fishing-map/features/vessel/VesselActivity.tsx
> +          onClick={(e) =>
yes, no problem

2023-07-01 16:17 UTC, fertandil87 commented on apps/fishing-map/features/regions/regions.slice.ts
> +        GFWAPI.fetch<Region[]>(`${apiUrl}/public-eez-areas/user-context-layer-v1`, options),
I forget your idea about this, we can do it in a different PR

2023-07-01 16:20 UTC, fertandil87 commented on apps/fishing-map/features/vessel/activity/ActivityDataAndTerminology.tsx
> +import { Fragment } from 'react'
maybe yes, maybe no, I removed for the moment

2023-07-01 16:21 UTC, fertandil87 commented on apps/fishing-map/package.json
> +    "react-virtualized-auto-sizer": "^1.0.7",
finally used for activity by type, not needed in activity by voyage

2023-07-03 12:19 UTC, j8seangel requested changes
In general, it seems a bit better, but I think there is still a lot of work of cleaning.
It is great to recover the virtualized list, but remember the event info is not in a modal.

2023-07-03 12:35 UTC, fertandil87 commented on apps/fishing-map/features/vessel/activity/activity-by-type/ActivityByType.tsx
> +          {expandedGroup === eventType && events[eventType]?.events.length && (
I didn't see any 0 but I take a look closer

2023-07-04 14:23 UTC, fertandil87 commented on apps/fishing-map/features/vessel/activity/activity-by-type/ActivityItem.tsx
I removed logic so it wasn't doing nothing specially now

2023-07-04 14:36 UTC, fertandil87 commented on apps/fishing-map/features/vessel/activity/activity-by-voyage/activity-by-voyage.slice.ts
> +  initialized: false,
refactored all the slice

2023-07-04 14:43 UTC, fertandil87 commented on apps/fishing-map/features/vessel/activity/activity-by-voyage/activity-by-voyage.slice.ts
yes, everything is different, the only common thing that they have is the final Event itself

2023-07-18 15:32 UTC, merged