add the actual endpoints to get vessel details
GlobalFishingWatch/frontend pull request #305
Opened 2021-02-10 15:00 UTC by fertandil87

https://globalfishingwatch.atlassian.net/browse/VH-53 (the branch name is wrong sorry)

2021-02-11 21:23 UTC, rdgfuentes requested changes
Comments below. It would be great to start adding some tests too

2021-02-12 20:34 UTC, fertandil87 commented on applications/vessel-history/src/features/profile/Profile.tsx
> +    }
yes, this was a future improvement, I just added the endpoints to continue working then on that

2021-02-12 20:35 UTC, fertandil87 commented on applications/vessel-history/src/features/profile/Profile.tsx
> +  const fetchTMTData = async (id: string) => {
that is another ticket

2021-02-12 20:37 UTC, fertandil87 commented on applications/vessel-history/src/features/profile/Profile.tsx
> +            <p>+4 previous names</p>
managing and rendering data for another PR

2021-02-12 20:38 UTC, fertandil87 commented on applications/vessel-history/src/features/profile/Profile.tsx
> +    },
we will have a PR for this tabs

2021-02-12 20:38 UTC, fertandil87 commented on applications/vessel-history/src/features/profile/components/Info.tsx
> +  const vessel = props.vessel
not understand

2021-02-17 15:15 UTC, rdgfuentes commented on applications/vessel-history/src/features/profile/Profile.tsx
> +    },
I'm saying that the content of the tabs Activity and MAP should be just a message with the text "Coming Soon!"

2021-02-17 15:21 UTC, fertandil87 commented on applications/vessel-history/src/features/profile/Profile.tsx
> +    },
ok

2021-02-17 15:35 UTC, rdgfuentes commented on applications/vessel-history/src/features/profile/components/Info.tsx
> +  const vessel = props.vessel
I'm saying that we are not displaying any vessel data coming from the API. All the vessel data that this component is displaying is hardcoded.

2021-02-17 15:37 UTC, closed without merging