add and edit custom draw areas
GlobalFishingWatch/frontend pull request #963
Opened 2021-09-21 13:37 UTC by j8seangel

✏️ 🗺️ 

https://user-images.githubusercontent.com/10500650/134697967-6f1a2736-51c3-40d6-896c-2fa6a5b8bcf6.mp4

2021-09-23 14:31 UTC, j8seangel commented on applications/fishing-map/src/features/map/MapDraw.tsx
> +      <div ref={containerRef} className={cx(styles.container, { [styles.hidden]: !editorMode })}>
I need the dom element to be present and ensure it is mounted so the eventManager recognises it

2021-09-27 14:25 UTC, nerik requested changes
Wow, this is super ambitious 👍 
At this rythtm ESRI is going to buy GFW next year.

A bunch of things:

![Screenshot 2021-09-27 at 16 04 05](https://user-images.githubusercontent.com/1583415/134924621-151a5a46-f3d5-41fb-a599-90dbde1e84d9.png)
We should not let user draw polygons with self-intersections IMHO: we will have bugs, crashes, or worse, wrong analyses and stuff that silently fails.
Maybe not for now as long as it's GFW-users only, but I'd have a look whenever possible

- It's not obvious the polygons can be moved, which is a shame because it's a great feature. However at first glance I'm not sure how to access polygons hover state which could be used to display a custom cursor or tooltip.  

- Drawing mode conflicts with ruler editing, disable ruler when drawing and vice-versa

- User should be alerted when saving, that further edits are not possible

2021-09-27 14:25 UTC, nerik commented on applications/fishing-map/src/features/map/MapDraw.tsx
> +                value={newPointLatitude || currentEditHandle[1]}
It's problematic IMHO that the user is not able to enter coordinates with the keyboard - and here's the culprit

2021-09-27 14:25 UTC, nerik commented on applications/fishing-map/src/features/app/App.tsx
> +          isOpen={sidebarOpen && drawMode === 'disabled'}
I don't like `drawMode` to be used in App when it's not a concern of App. Maybe another selector such as `selectIsDrawing` which would be a boolean.

2021-09-27 14:25 UTC, nerik commented on applications/fishing-map/src/features/map/Map.tsx
> +          onClick={drawMode !== 'disabled' ? undefined : currentClickCallback}
Same comment as in https://github.com/GlobalFishingWatch/frontend/pull/963/files#diff-f77b7b230099b5b21a1538c91c906e381bbaf58f88ed8aa3a4a4d696a483c46eR209

2021-09-27 14:25 UTC, nerik commented on applications/fishing-map/src/features/map/MapDraw.tsx
> +                step="0.01"
Also this: 0.01 is much too big at zoom 10, and much too small at zoom 3. Either provide an option to input by keyboard (preferred), or adapt step to zoom level (meh)

2021-09-27 14:25 UTC, nerik commented on applications/fishing-map/src/features/map/map.draw.utils.ts
> +            coordinate.map((points) => points.map((point) => Math.round(point * 100000) / 100000))
It would be nice to try to enforce a standard re this. Maybe start by moving this to a util + a config const?

2021-09-27 14:25 UTC, nerik commented on applications/fishing-map/src/features/timebar/Timebar.tsx
> +  if (!start || !end || drawMode !== 'disabled') return null
Re https://github.com/GlobalFishingWatch/frontend/pull/963/files#diff-f77b7b230099b5b21a1538c91c906e381bbaf58f88ed8aa3a4a4d696a483c46eR209

2021-09-29 13:55 UTC, j8seangel commented
> We should not let user draw polygons with self-intersections IMHO: we will have bugs, crashes, or worse, wrong analyses and stuff that silently fails. 🪄 
![image](https://user-images.githubusercontent.com/10500650/135272543-ede3367a-c0ae-4c37-8702-604ed969bd8d.png)

2021-09-29 13:56 UTC, merged